# Generated by Django 5.0.6 on 2024-06-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodred2', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
