# Generated by Django 5.0.6 on 2024-06-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodred2', '0003_feedbackform_delete_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedbackForm',
            new_name='Feedback',
        ),
    ]
