# Generated by Django 5.0.6 on 2024-06-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodred2', '0004_rename_feedbackform_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
