# Generated by Django 5.0.6 on 2024-06-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register1', '0002_profile_birth_date_profile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='password2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
