# Generated by Django 5.0.6 on 2024-06-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register1', '0003_rename_bio_profile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
