# Generated by Django 5.0.6 on 2024-06-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register1', '0005_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
